-- Atlas Hub Snowflake Platform DDL
-- Run as SYSADMIN (see docs/production-readiness/onboarding.md)

-- =============================================================================
-- DATABASES
-- =============================================================================

CREATE DATABASE IF NOT EXISTS RAW_DEV COMMENT = 'Raw landing zone - dev';
CREATE DATABASE IF NOT EXISTS RAW_STAGING COMMENT = 'Raw landing zone - staging';
CREATE DATABASE IF NOT EXISTS RAW_PROD COMMENT = 'Raw landing zone - production';

CREATE DATABASE IF NOT EXISTS ANALYTICS_DEV COMMENT = 'Transformed analytics - dev';
CREATE DATABASE IF NOT EXISTS ANALYTICS_STAGING COMMENT = 'Transformed analytics - staging';
CREATE DATABASE IF NOT EXISTS ANALYTICS_PROD COMMENT = 'Transformed analytics - production';

CREATE DATABASE IF NOT EXISTS GOVERNANCE_PROD COMMENT = 'Audit, quality, lineage metadata';

-- =============================================================================
-- SCHEMAS — RAW (example: PROD)
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS RAW_PROD.SALESFORCE COMMENT = 'Fivetran Salesforce connector';
CREATE SCHEMA IF NOT EXISTS RAW_PROD.HUBSPOT COMMENT = 'Fivetran HubSpot connector';
CREATE SCHEMA IF NOT EXISTS RAW_PROD.STRIPE COMMENT = 'Fivetran Stripe connector';
CREATE SCHEMA IF NOT EXISTS RAW_PROD.NETSUITE COMMENT = 'Fivetran NetSuite connector';
CREATE SCHEMA IF NOT EXISTS RAW_PROD.WORKDAY COMMENT = 'Fivetran Workday connector';
CREATE SCHEMA IF NOT EXISTS RAW_PROD.ZENDESK COMMENT = 'Fivetran Zendesk connector';
CREATE SCHEMA IF NOT EXISTS RAW_PROD.GOOGLE_ANALYTICS COMMENT = 'Fivetran GA connector';
CREATE SCHEMA IF NOT EXISTS RAW_PROD.S3_LANDING COMMENT = 'Custom API / event parquet loads';

-- =============================================================================
-- SCHEMAS — ANALYTICS (PROD)
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.STG_SALESFORCE;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.STG_HUBSPOT;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.STG_STRIPE;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.STG_NETSUITE;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.STG_WORKDAY;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.STG_ZENDESK;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.STG_PRODUCT;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.INT;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.MART_FINANCE;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.MART_SALES;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.MART_MARKETING;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.MART_PRODUCT;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.MART_HR;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.SEMANTIC;

-- =============================================================================
-- WAREHOUSES
-- =============================================================================

CREATE WAREHOUSE IF NOT EXISTS WH_ETL_PROD
  WAREHOUSE_SIZE = 'LARGE'
  AUTO_SUSPEND = 120
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'dbt ETL and Snowpipe loads';

CREATE WAREHOUSE IF NOT EXISTS WH_BI_PROD
  WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'BI and semantic API queries';

CREATE WAREHOUSE IF NOT EXISTS WH_ADHOC_PROD
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Analyst ad-hoc queries';

CREATE WAREHOUSE IF NOT EXISTS WH_ML_PROD
  WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND = 120
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Databricks write-back and ML features';

-- Resource monitor (adjust credit quota per environment)
CREATE RESOURCE MONITOR IF NOT EXISTS RM_PROD_MONTHLY
  WITH CREDIT_QUOTA = 5000
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 80 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE WH_ETL_PROD SET RESOURCE_MONITOR = RM_PROD_MONTHLY;
ALTER WAREHOUSE WH_BI_PROD SET RESOURCE_MONITOR = RM_PROD_MONTHLY;
