-- RBAC: Roles, grants, and hierarchy
-- Principle of least privilege with role inheritance

-- =============================================================================
-- ROLE HIERARCHY
-- =============================================================================
-- ATLAS_ADMIN → ATLAS_ENGINEER → ATLAS_TRANSFORMER
-- ATLAS_BI → ATLAS_ANALYST
-- ATLAS_FINANCE, ATLAS_SALES, ATLAS_MARKETING, ATLAS_HR (domain read)
-- ATLAS_API_SERVICE (semantic API service account)

CREATE ROLE IF NOT EXISTS ATLAS_ADMIN COMMENT = 'Platform administrators';
CREATE ROLE IF NOT EXISTS ATLAS_ENGINEER COMMENT = 'Data engineers - full dev/staging';
CREATE ROLE IF NOT EXISTS ATLAS_TRANSFORMER COMMENT = 'dbt service role - write analytics schemas';
CREATE ROLE IF NOT EXISTS ATLAS_BI COMMENT = 'BI developers';
CREATE ROLE IF NOT EXISTS ATLAS_ANALYST COMMENT = 'General analysts - masked PII';
CREATE ROLE IF NOT EXISTS ATLAS_FINANCE COMMENT = 'Finance team - finance marts';
CREATE ROLE IF NOT EXISTS ATLAS_SALES COMMENT = 'Sales ops - sales marts + territory RLS';
CREATE ROLE IF NOT EXISTS ATLAS_MARKETING COMMENT = 'Marketing - marketing marts';
CREATE ROLE IF NOT EXISTS ATLAS_HR COMMENT = 'HR - HR marts with PII policies';
CREATE ROLE IF NOT EXISTS ATLAS_API_SERVICE COMMENT = 'Metrics API read-only service';
CREATE ROLE IF NOT EXISTS ATLAS_AUDITOR COMMENT = 'Read audit/governance only';

GRANT ROLE ATLAS_ENGINEER TO ROLE ATLAS_ADMIN;
GRANT ROLE ATLAS_TRANSFORMER TO ROLE ATLAS_ENGINEER;
GRANT ROLE ATLAS_BI TO ROLE ATLAS_ENGINEER;
GRANT ROLE ATLAS_ANALYST TO ROLE ATLAS_BI;
GRANT ROLE ATLAS_FINANCE TO ROLE ATLAS_ANALYST;
GRANT ROLE ATLAS_SALES TO ROLE ATLAS_ANALYST;
GRANT ROLE ATLAS_MARKETING TO ROLE ATLAS_ANALYST;
GRANT ROLE ATLAS_HR TO ROLE ATLAS_HR;  -- direct grant, not via analyst

-- =============================================================================
-- WAREHOUSE GRANTS
-- =============================================================================

GRANT USAGE ON WAREHOUSE WH_ETL_PROD TO ROLE ATLAS_TRANSFORMER;
GRANT USAGE ON WAREHOUSE WH_BI_PROD TO ROLE ATLAS_BI;
GRANT USAGE ON WAREHOUSE WH_BI_PROD TO ROLE ATLAS_API_SERVICE;
GRANT USAGE ON WAREHOUSE WH_ADHOC_PROD TO ROLE ATLAS_ANALYST;
GRANT USAGE ON WAREHOUSE WH_ML_PROD TO ROLE ATLAS_TRANSFORMER;

-- =============================================================================
-- DATABASE GRANTS — PROD
-- =============================================================================

-- RAW: engineers read; transformer read for dbt sources
GRANT USAGE ON DATABASE RAW_PROD TO ROLE ATLAS_ENGINEER;
GRANT USAGE ON DATABASE RAW_PROD TO ROLE ATLAS_TRANSFORMER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RAW_PROD TO ROLE ATLAS_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN DATABASE RAW_PROD TO ROLE ATLAS_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN DATABASE RAW_PROD TO ROLE ATLAS_TRANSFORMER;

-- ANALYTICS: transformer write; domain roles read specific schemas
GRANT USAGE ON DATABASE ANALYTICS_PROD TO ROLE ATLAS_TRANSFORMER;
GRANT ALL ON ALL SCHEMAS IN DATABASE ANALYTICS_PROD TO ROLE ATLAS_TRANSFORMER;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE ANALYTICS_PROD TO ROLE ATLAS_TRANSFORMER;

GRANT USAGE ON SCHEMA ANALYTICS_PROD.MART_FINANCE TO ROLE ATLAS_FINANCE;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS_PROD.MART_FINANCE TO ROLE ATLAS_FINANCE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_PROD.MART_FINANCE TO ROLE ATLAS_FINANCE;

GRANT USAGE ON SCHEMA ANALYTICS_PROD.MART_SALES TO ROLE ATLAS_SALES;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS_PROD.MART_SALES TO ROLE ATLAS_SALES;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_PROD.MART_SALES TO ROLE ATLAS_SALES;

GRANT USAGE ON SCHEMA ANALYTICS_PROD.MART_MARKETING TO ROLE ATLAS_MARKETING;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS_PROD.MART_MARKETING TO ROLE ATLAS_MARKETING;

GRANT USAGE ON SCHEMA ANALYTICS_PROD.MART_HR TO ROLE ATLAS_HR;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS_PROD.MART_HR TO ROLE ATLAS_HR;

GRANT USAGE ON SCHEMA ANALYTICS_PROD.SEMANTIC TO ROLE ATLAS_API_SERVICE;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS_PROD.SEMANTIC TO ROLE ATLAS_API_SERVICE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_PROD.SEMANTIC TO ROLE ATLAS_API_SERVICE;

-- Service users
CREATE USER IF NOT EXISTS SVC_DBT_PROD
  DEFAULT_ROLE = ATLAS_TRANSFORMER
  DEFAULT_WAREHOUSE = WH_ETL_PROD
  COMMENT = 'dbt Cloud / CI service account';

CREATE USER IF NOT EXISTS SVC_METRICS_API_PROD
  DEFAULT_ROLE = ATLAS_API_SERVICE
  DEFAULT_WAREHOUSE = WH_BI_PROD
  COMMENT = 'Semantic metrics API';

GRANT ROLE ATLAS_TRANSFORMER TO USER SVC_DBT_PROD;
GRANT ROLE ATLAS_API_SERVICE TO USER SVC_METRICS_API_PROD;
